name: CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        name: [linux-docker]
        include:
          - name: linux-docker
            os: ubuntu-latest
      # complete all jobs
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v1
        with:
          path: cache
          key: ${{ matrix.name }}-build-${{ github.sha }}
          # fall back to (latest) previous cache
          restore-keys: |
            ${{ matrix.name }}-build
      - name: Make ubuntu-build docker image
        run: docker build -t pirateteam/ubuntu-dev images/ubuntu-build
      - name: Build
        run: |
          mkdir -p cache
          mkdir -p dist
          docker run -i \
            --cpus=2 \
            --memory=16G \
            --mount type=bind,src=`pwd`/images/ubuntu-llvm,dst=/root/dist \
            --mount type=bind,src=`pwd`/cache,dst=/root/cache \
            --mount type=bind,src=`pwd`,dst=/root/pirate-llvm,ro \
            -w /root \
            pirateteam/ubuntu-dev \
            /root/pirate-llvm/scripts/docker-internal.sh
      - name: Make pirate-llvm docker image
        run: docker build -t pirateteam/ubuntu-llvm images/ubuntu-llvm
      - name: Post docker images
        run: |
          echo ${{ secrets.docker_password }} | docker login -u gapspirateteam --password-stdin
          docker push pirateteam/ubuntu-dev
          docker push pirateteam/ubuntu-llvm
        if: github.ref == 'refs/heads/master'
