name: CI

on: [push]

jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Make pirateteam/build docker image
        run: |
          docker build -t pirateteam/build images/build
          docker save pirateteam/build | gzip > latest.tar.gz
      - name: Save build image artifact
        uses: actions/upload-artifact@v1
        with:
          name: pirateteam_build
          path: latest.tar.gz
      - name: Post docker images
        run: |
          echo ${{ secrets.docker_password }} | docker login -u gapspirateteam --password-stdin
          docker push pirateteam/build
        if: github.ref == 'refs/heads/master'
  build_llvm:
    runs-on: ubuntu-latest
    needs: build_image
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download build image artifact from previous job
        uses: actions/download-artifact@v1
        with:
          name: pirateteam_build
      - name: Cache
        uses: actions/cache@v1
        with:
          path: cache
          key: linux-docker-build-${{ github.sha }}
          # fall back to (latest) previous cache
          restore-keys: linux-docker-build
      - name: Load docker image
        run: docker load < pirateteam_build/latest.tar.gz
      - name: Run cmake
        run: |
          mkdir -p build
          mkdir -p cache
          mkdir -p dist
          docker run -i \
            --cpus=2 \
            --memory=16G \
            --mount type=bind,src=`pwd`/build,dst=/root/build  \
            --mount type=bind,src=`pwd`/cache,dst=/root/cache \
            --mount type=bind,src=`pwd`/images/llvm-ubuntu,dst=/root/dist \
            --mount type=bind,src=`pwd`,dst=/root/pirate-llvm,ro \
            -w /root/build \
            pirateteam/build \
            /root/pirate-llvm/scripts/docker-cmake.sh Release
      - name: Run build
        run: |
          docker run -i \
            --cpus=2 \
            --memory=16G \
            --mount type=bind,src=`pwd`/build,dst=/root/build  \
            --mount type=bind,src=`pwd`/cache,dst=/root/cache \
            --mount type=bind,src=`pwd`/dist,dst=/root/dist \
            --mount type=bind,src=`pwd`,dst=/root/pirate-llvm,ro \
            -w /root/build \
            -e CCACHE_DIR=/root/cache/ccache \
            -e CCACHE_COMPRESS=true \
            -e CCACHE_MAXSIZE=400M \
            pirateteam/build \
            ninja -j 2 install-distribution
          cp -r `pwd`/dist `pwd`/images/llvm-ubuntu/pirate-llvm
          cp -r `pwd`/dist `pwd`/images/llvm-rh7/pirate-llvm
#      - name: Run tests
#        run: |
#          docker run -i \
#            --cpus=2 \
#            --memory=16G \
#            --mount type=bind,src=`pwd`/build,dst=/root/build  \
#            --mount type=bind,src=`pwd`/cache,dst=/root/cache \
#            --mount type=bind,src=`pwd`/images/llvm-ubuntu,dst=/root/dist \
#            --mount type=bind,src=`pwd`,dst=/root/pirate-llvm,ro \
#            -w /root/build \
#            -e CCACHE_DIR=/root/cache/ccache \
#            -e CCACHE_COMPRESS=true \
#            -e CCACHE_MAXSIZE=400M \
#            pirateteam/build \
#            ninja check-all
      - name: Save LLVM dist
        uses: actions/upload-artifact@v1
        with:
          name: pirate-llvm
          path: images/llvm-ubuntu/pirate-llvm
      - name: Make pirateteam/llvm-ubuntu docker image
        run: docker build -t pirateteam/llvm-ubuntu images/llvm-ubuntu
      - name: Make pirateteam/llvm-rh7 docker image
        run: docker build -t pirateteam/llvm-rh7 images/llvm-rh7
      - name: Post docker images
        run: |
          echo ${{ secrets.docker_password }} | docker login -u gapspirateteam --password-stdin
          docker push pirateteam/llvm-ubuntu
          docker push pirateteam/llvm-rh7
        if: github.ref == 'refs/heads/master'
