name: CI

on:
  push:
  release:
    type: [created]

jobs:
  build_image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        name: [ubuntu, centos7]
        include:
          - name: ubuntu
            os: ubuntu
          - name: centos7
            os: centos7
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Make pirateteam/build docker image
        run: |
          docker build -t pirateteam/build-${{matrix.os}} images/build-${{matrix.os}}
          docker save pirateteam/build-${{matrix.os}} | gzip > latest.tar.gz
      - name: Save build image artifact
        uses: actions/upload-artifact@v1
        with:
          name: pirateteam_build_${{matrix.os}}
          path: latest.tar.gz
      - name: Post build docker image
        run: |
          echo ${{ secrets.docker_password }} | docker login -u gapspirateteam --password-stdin
          docker push pirateteam/build-${{matrix.os}}:${{github.event.release.tag_name}}
        if: github.event_name == 'release'
      - name: Cache
        uses: actions/cache@v1
        with:
          path: cache
          key: build-${{matrix.name}}-${{github.sha}}
          # fall back to (latest) previous cache
          restore-keys: build-${{matrix.name}}
      - name: Run cmake
        run: |
          mkdir -p build
          mkdir -p cache
          mkdir -p dist
          docker run -i \
            --cpus=2 \
            --memory=16G \
            --mount type=bind,src=`pwd`/build,dst=/root/build  \
            --mount type=bind,src=`pwd`/cache,dst=/root/cache \
            --mount type=bind,src=`pwd`/images/llvm-ubuntu,dst=/root/dist \
            --mount type=bind,src=`pwd`,dst=/root/pirate-llvm,ro \
            -w /root/build \
            pirateteam/build-${{matrix.os}} \
            /root/pirate-llvm/scripts/docker-cmake.sh Release
      - name: Run build
        run: |
          docker run -i \
            --cpus=2 \
            --memory=16G \
            --mount type=bind,src=`pwd`/build,dst=/root/build  \
            --mount type=bind,src=`pwd`/cache,dst=/root/cache \
            --mount type=bind,src=`pwd`/dist,dst=/root/dist \
            --mount type=bind,src=`pwd`,dst=/root/pirate-llvm,ro \
            -w /root/build \
            -e CCACHE_DIR=/root/cache/ccache \
            -e CCACHE_COMPRESS=true \
            -e CCACHE_MAXSIZE=400M \
            pirateteam/build-${{matrix.os}} \
            make -j 2 install-distribution
      - name: Save LLVM dist
        uses: actions/upload-artifact@v1
        with:
          name: pirate-llvm-${{ matrix.os }}
          path: dist/pirate-llvm
# TODO: Enable these once we are building LLVM
#      - name: Make pirateteam/llvm docker image
#        run: docker build -t pirateteam/llvm-${{matrix.os}} images/llvm-${{matrix.os}}
#      - name: Post docker images
#        run: |
#          echo ${{ secrets.docker_password }} | docker login -u gapspirateteam --password-stdin
#          docker push pirateteam/llvm-${{matrix.os}}:${{github.event.release.tag_name}}
#        if: github.event_name == 'release'
